name: Deploy Python Bot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy source to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
          source: "."
          target: "~/my-python-app"
          rm: true

      - name: SSH and run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_SSH_PASSPHRASE }}
          script: |
            set -e
            sudo apt-get update
            sudo apt-get install -y python3-venv
            cd ~/my-python-app/application/discord-bot
            if [ ! -d venv ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
            cat <<EOF > .env
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            IGNORED_ROLE_IDS=${{ secrets.IGNORED_ROLE_IDS }}
            EOF
            chmod 600 .env
            chmod +x run.sh
            nohup ./run.sh > bot.log 2>&1 &