name: Terraform GCP Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/gcp/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure/gcp
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure/gcp
        run: terraform plan

      - name: Terraform Apply
        working-directory: infrastructure/gcp
        run: terraform apply -auto-approve